apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
     app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: apache
        image: apache
        ports:
        - containerPort: 80